apiVersion: apps/v1
kind: Deployment
metadata:
  name: studio-rs
  namespace: noel-ns
  labels:
    app: studio
spec:
  replicas: 5
  selector:
    matchLabels:
      app: std
  template:
    metadata:
      labels:
        app: std
    spec:
      containers:
        - name: studio-container1
          image: muralisocial123/ey-cart:v1.1.0 
          ports:
            - containerPort: 3000